"""Durable, event-sourced execution core for CoPenguin."""

from .artifacts import ArtifactCAS, ArtifactRef
from .coordinator import ActiveRun, TaskHandle, ThreadCoordinator
from .errors import (
    ArtifactCorruption,
    ArtifactNotFound,
    ConcurrencyConflict,
    IdempotencyConflict,
    InvalidTransition,
    NotFound,
    ReconciliationRequired,
    ResourceConflict,
    RuntimeInvariantError,
    StaleLease,
)
from .inbox import (
    ConservativeInboxRouter,
    InboxCoordinator,
    InboxMessage,
    InboxRoute,
    IngressAdapter,
    IngressResult,
    RoutingContext,
)
from .models import (
    AccessMode,
    ActionClaim,
    ActionIntent,
    ActionReceipt,
    ActionStatus,
    ApprovalRequest,
    ApprovalState,
    AttentionState,
    DesiredState,
    EventDraft,
    EventEnvelope,
    InboxRecord,
    InboxRouteState,
    InboxRouteType,
    JobState,
    ReceiptOutcome,
    ResourceLease,
    RunProjection,
    RunState,
    SchedulerJob,
    TaskSubmission,
    ThreadProjection,
    ThreadState,
    WorkerClaim,
)
from .repository import SQLiteRuntimeRepository
from .snapshots import AgentSnapshot, ContextItem, ContextManifest, SnapshotStore, TaskSnapshot

__all__ = [
    "AccessMode",
    "ActionClaim",
    "ActionIntent",
    "ActionReceipt",
    "ActionStatus",
    "ApprovalRequest",
    "ApprovalState",
    "ActiveRun",
    "AgentSnapshot",
    "ArtifactCAS",
    "ArtifactCorruption",
    "ArtifactNotFound",
    "ArtifactRef",
    "AttentionState",
    "ConcurrencyConflict",
    "ContextItem",
    "ContextManifest",
    "ConservativeInboxRouter",
    "DesiredState",
    "EventDraft",
    "EventEnvelope",
    "IdempotencyConflict",
    "IngressAdapter",
    "IngressResult",
    "InboxCoordinator",
    "InboxMessage",
    "InboxRecord",
    "InboxRoute",
    "InboxRouteState",
    "InboxRouteType",
    "InvalidTransition",
    "JobState",
    "NotFound",
    "ResourceConflict",
    "ReconciliationRequired",
    "ResourceLease",
    "ReceiptOutcome",
    "RunProjection",
    "RunState",
    "RoutingContext",
    "RuntimeInvariantError",
    "SchedulerJob",
    "SQLiteRuntimeRepository",
    "StaleLease",
    "SnapshotStore",
    "TaskSnapshot",
    "TaskSubmission",
    "TaskHandle",
    "ThreadProjection",
    "ThreadCoordinator",
    "ThreadState",
    "WorkerClaim",
]

__version__ = "0.1.0"
